[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci',
  'cd backend && npm ci',
  'cd frontend && npm ci'
]

[phases.build]
cmds = [
  'cd frontend && npm run build'
]

[start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production'
PORT = '3002'