name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude'))
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
    - name: Claude Code Review
      uses: anthropics/claude-code-action@v1
      with:
        # Use either ANTHROPIC_API_KEY or CLAUDE_CODE_OAUTH_TOKEN
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        # claude-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}